### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by mattgriff** [madisongh/meta-tegra#24]
I would like to contribute to this but I'm not sure where to start. Is there an IRC channel on freenode that anyone here frequents where we can chat? I have a TX1 I'm planning on using for a project but would like to help out.

**Comment by madisongh** [comment]
Sorry for the delayed response on this... I'd certainly appreciate any help.  I don't have an IRC channel set up for discussions, but I do have a freenode account (madisox) and if folks would find it helpful we could create a channel there for this.

Otherwise you can file issues and send pull requests here.  I'd certainly welcome more contributors!
