### ISSUE TITLE
Cannot find CUDA libraries at runtime

### ISSUE THREAD

**Issue by avishorp** [madisongh/meta-tegra#28]
The CUDA libraries are installed in the image, but are located at a non-standard location (/usr/local/cuda-X.Y/lib) and therefore cannot be found at runtime. What's the best way to solve it? Add a line to ld.so.conf? Create symbolic links for /lib? How can I implement those solutions?

**Comment by madisongh** [comment]
If you have a recipe for cross-building a package that uses CUDA, have it `inherit cuda` and that bbclass should update LDFLAGS with `-rpath` linker options so the resulting ELF binary has an RPATH that points to the path under `/usr/local`.

If you are building things other ways (e.g. on the target directly), you could set the LD_LIBRARY_PATH environment variable to point to that location.  The ld.so.conf approach could work, too.

I was hesitant to put the libraries under `/lib` or `/usr/lib` directly, or create symlinks there, mainly because I wasn't sure how dependent the CUDA toolkit was on having the path be exactly as NVIDIA provides it.
