### ISSUE TITLE
cant locate kernel-module-tun

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/meta-tegra#319]
i have an application that RDEPENDS kernel-module-tun for tun/tap however it cants be found...
oe-repo: using metadata from Fri 22 May 2020 02:10:12 AM UTC.
Last metadata expiration check: 0:00:01 ago on Fri 22 May 2020 02:10:12 AM UTC.
No module defaults found
No match for argument: kernel-module-tun
Error: Unable to find a match

**Comment by madisongh** [comment]
That driver is configured to be built into the kernel for tegra platforms, rather than being built as a separate module, so there is no separate package for it.  Best practice for specifying a dependency on a kernel driver is to use RRECOMMENDS instead of RDEPENDS - that way, if it's built in, there's no failure, but if it is a module, the package for the module will get installed.

**Comment by outbackdingo** [comment]
noted. Thanks, its functioning now.
