### ISSUE TITLE
Image type "tegraflash" fails because of rootfs alignement 

### ISSUE THREAD

**Issue by stammw** [madisongh/meta-tegra#46]
Hello,

I'm working with `krogoth-l4t-r24.2.1` branch and I had an error about ext3 rootfs alignment during do_image_tegraflash : 

```
DEBUG: Executing shell function do_image_tegraflash
4.0K	/home/jc/oe-core/build/tmp-glibc/deploy/images/jetson-tx1/core-image-minimal-jetson-tx1.ext3
size of /home/jc/oe-core/build/tmp-glibc/deploy/images/jetson-tx1/core-image-minimal-jetson-tx1.ext3 is not mulple of 4096.
```

I found that `IMAGE_ROOTFS_ALIGNMENT ?= "4096"` line, in `meta-tegra/classes/image_types_tegra.bbclass`, fails to override the value assigned in `meta/classes/image_types.bbclass`.

As this variable is in KiB, i beleive the correct value would be `4`.

Would you accept a pull request on this matter?

**Comment by madisongh** [comment]
Yeah, the setting works better if it's added to the machine configuration, as was done in 19e05df33dcc5703120febe54ac8d90cb44c73ea.

Funny that you mention the units, I hadn't noticed that before....  I've used it with other BSP layers, too, which always set it to something like 1024 or 4096, and I just assumed that was bytes rather than KiB.  If 4 works, great.    I should probably update that in master, too.
