### ISSUE TITLE
Systemd Serial ttyS1 

### ISSUE THREAD

**Issue by BarbareBzhdev** [madisongh/meta-tegra#84]
Hi @madisongh ,
I wish your advices into my meta if it's OK for you. I work on Spacely connecttech board and create kernel compatible with merge between your linux-tegra and CTI kernel. For this time I can use all devices (4G modem, CSI, USB, eth, ...). I can dialog too with serial 0 (console serial) but I cannot with Serial 1. How can I fix it and set my ttyS1 with Systemd ?

I try to set ma local.conf with SERIAL_CONSOLE_append = " 921600 ttyS1" but without result?

Are you any Idea?

Thanks for your help
PS: Great job for your meta and linux-tegra, it's a realy good work ! :grin:

**Comment by madisongh** [comment]
Is the problem
1. there is no /dev/ttyS1
2. there is, but it doesn't work properly
3. it's there and works, and you want to use that as the console

For 1 or 2, track down the `serial@XXXXXXXX` address for that second UART and double-check that the device tree entry is "okay" and not "disabled", and check the kernel logs to see if the driver reports an issue or possibly a different name for the device.

For 3, assuming that NVIDIA's kernel early boot actually supports using the other UART as the console, you could try just setting SERIAL_CONSOLE instead of appending to it.

**Comment by BarbareBzhdev** [comment]
Thks Matt. It's work now. Realy thks for your advices :+1:
